"""empty message

Revision ID: 549b0a4c32b6
Revises: 4c117bfbbca7
Create Date: 2021-11-01 13:56:16.473679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '549b0a4c32b6'
down_revision = '4c117bfbbca7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))
    
    op.execute('UPDATE todos SET completed = False WHERE completed IS NULL;')

    op.alter_column('todos', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
